name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x.x
 
    - name: Calculate Version Parameters
      id: version
      run: |
        template=`cat ./VERSION`
        shortsha=$(git rev-parse --short ${{ github.sha }})
        echo "template=$template" >> $GITHUB_OUTPUT 
        echo "shortsha=$shortsha" >> $GITHUB_OUTPUT
        echo "semver=${template//{build}/$shortsha}+sha.$shortsha"
        
 
    - name: Build
      working-directory: ./src
      run: dotnet pack --configuration Release /p:PackageVersion=1.0.${{github.run_number}}+sha.${{steps.version.outputs.shortsha}}
    
